name: build-project-workflow

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Fat Jar
        run: sbt assembly
      - name: S3 Upload Jar
        uses: arthurgalerneau/tp2_sparkesme@main
